<?php

namespace Database\Seeders;

use App\Models\FAQ;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FAQSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $faqs = [
            ['user_id' => 1, 'question' => 'What is Whales Market?', 'answer' => 'Whales Market is an online marketplace that allows users to buy and sell products, both digital and physical. It provides a platform for sellers to list their products after verification by admins or mods.'],
            ['user_id' => 1, 'question' => 'How can I sell (open a store) on Whales Market?', 'answer' => 'To open a store on Whales Market, you need a store key (64-128 characters) to encrypt your information. Click on the store icon, provide your information and store key, and ensure your 2FA is enabled and matches your public name. You can purchase or ask for waiver a store key in the "Setting > store key" and receive a notification with your store key after payment or waiver accepted.'],
            ['user_id' => 1, 'question' => 'Can I list both digital and physical products in my store?', 'answer' => 'Yes, Whales Market allows stores to list both digital and physical products. Whether you are offering digital content or tangible items, you can showcase your products within your verified store on the platform.'],
            ['user_id' => 1, 'question' => 'What are the guidelines for listing products on Whales Market?', 'answer' => 'Stores are required to adhere to specific guidelines when listing products on Whales Market. These guidelines may include providing accurate product descriptions, using high-quality images, removing meta data from images and ensuring that the products align with the theme of the marketplace rules.'],
            ['user_id' => 1, 'question' => 'How does the moderation process work for product listings?', 'answer' => 'The moderation process involves a review of product listings to ensure they meet the platform\'s standards. This includes verifying the accuracy of product information, images, and adherence to content policies. Stores are notified of any necessary adjustments or approvals.'],
            ['user_id' => 1, 'question' => 'Are there any restrictions on the types of products that can be sold on Whales Market?', 'answer' => 'While Whales Market encourages a diverse range of products, there are many restrictions on certain items. Stores should review the platforms policies(rules) to understand any limitations on product categories or content.'],
            ['user_id' => 1, 'question' => 'Can I update my store information after it has been active?', 'answer' => 'Yes, sellers can update their store information, including product listings, even after the initial verification process. It is essential to keep your store details accurate and up-to-date to provide a positive experience for buyers.'],
            ['user_id' => 1, 'question' => 'How can buyers trust the authenticity of products on Whales Market?', 'answer' => 'Whales Markets verification process for sellers and product listings is designed to build trust. Buyers can look for store rating and reviews and ratings contribute to the overall transparency and reliability of the marketplace,.'],
            ['user_id' => 1, 'question' => 'What is the difference between a store and a regular user account on Whales Market?', 'answer' => 'A store on Whales Market is an advanced account type designed for sellers. It comes with a dedicated dashboard that provides powerful tools for managing products and sales. When your store is active, you have exclusive access to your personalized dashboard, limiting your interaction with the general marketplace features.'],
            ['user_id' => 1, 'question' => 'Can I still access the main market while my store is active?', 'answer' => 'No, when your store is active, your access is limited to the stores dashboard. This exclusive environment allows you to focus on managing your products, sales, and other essential tasks without being distracted by unrelated marketplace activities. If you wish to browse or participate in the main market, you can create another account specifically for that purpose.'],
            ['user_id' => 1, 'question' => 'What tools are available in the stores dashboard for sellers?', 'answer' => 'The stores dashboard on Whales Market is equipped with powerful tools tailored for sellers. These may include inventory management, order processing, sales analytics, and promotional features, store share access, coupons system and more. Sellers can efficiently handle their store operations and monitor their performance through a centralized and user-friendly interface.'],
            ['user_id' => 1, 'question' => 'What happens if my store is inactive or suspended?', 'answer' => 'If your store is inactive or suspended due to violations or other reasons, your access to the stores dashboard will be restricted. You may receive notifications and instructions on how to address the issues causing the inactivity. Resolving these issues will enable you to reactivate your store and regain access to the seller dashboard.'],
            ['user_id' => 1, 'question' => 'What is Vacation Mode on Whales Market?', 'answer' => 'Vacation Mode is a feature on Whales Market that allows sellers to temporarily deactivate their store. This is useful for sellers who anticipate being inactive for a specific period, such as vacations or temporary breaks.'],
            ['user_id' => 1, 'question' => 'How do I activate Vacation Mode for my store?', 'answer' => 'To activate Vacation Mode, log in to your store\'s dashboard, navigate to settings, and look for the Vacation Mode option, and set it.'],
            ['user_id' => 1, 'question' => 'Can I still access my store\'s dashboard while it\'s in Vacation Mode?', 'answer' => 'Yes, sellers can still access their store\'s dashboard while in Vacation Mode. However, the store will not be visible to buyers, and transactions will be temporarily disabled.'],
            ['user_id' => 1, 'question' => 'What happens to my existing listings and products during Vacation Mode?', 'answer' => 'While your store is in Vacation Mode, your existing listings and products will remain on the platform but will be temporarily hidden from buyers. This ensures that your store retains its presence, and buyers are aware of your temporary absence.'],
            ['user_id' => 1, 'question' => 'Are there any restrictions on how often I can use Vacation Mode?', 'answer' => 'Whales Market does not impose strict restrictions on the frequency of using Vacation Mode. Sellers can use this feature as needed, but it\'s recommended to use it judiciously to ensure a positive experience for both sellers and buyers.'],
            
            ['user_id' => 1, 'question' => ' What is the Dispute System on Whales Market?', 'answer' => 'The Dispute System on Whales Market is a comprehensive feature designed to facilitate quick and fair resolutions in case of conflicts between buyers and sellers. It acts as a mechanism to address issues related to transactions without the immediate involvement of a moderator.'],
            ['user_id' => 1, 'question' => 'How does the Dispute System work on Whales Market?', 'answer' => 'In the event of a dispute, either the buyer or the seller can initiate the resolution process through the Dispute System. The platform provides a user-friendly interface where users can submit details about the issue, including evidence such as messages, it also has a messaging system, with sleek functions.'],
            ['user_id' => 1, 'question' => 'What tools are available in the Dispute System for both buyers and sellers?', 'answer' => 'The Dispute System comes with a full set of features for both buyers and sellers. Users can present their case, provide evidence, and engage in communication directly through the system. This includes the ability to message, accept refunds, start partial refund, percentage system, decline partial, release funds, request mods, and more.'],
            ['user_id' => 1, 'question' => 'Can I request the assistance of a moderator in a dispute?', 'answer' => 'Yes, while the Dispute System is designed to allow users to resolve issues independently, there is an option to request moderator intervention. This button serves as a safety net, ensuring that if the dispute cannot be resolved directly between the parties, a moderator can step in to provide assistance and make a final decision.'],

            ['user_id' => 1, 'question' => 'What is the Whales Market Auto-Delete System?', 'answer' => 'The Whales Market Auto-Delete System is a feature designed to automatically remove specific types of messages after a designated period. This helps keep top security, conversations and transactions organized by removing outdated or completed information.'],
            ['user_id' => 1, 'question' => 'Which are subject to auto-deletion on Whales Market?', 'answer' => 'The Auto-Delete System targets read messages, completed transactions, closed disputes, and canceled orders. These are automatically removed from the platform after 15 days, streamlining the communication channels, reducing clutter and improving higher security.'],

            ['user_id' => 1, 'question' => 'What is the Auto-Cancellation System on Whales Market?', 'answer' => 'The Auto-Cancellation System on Whales Market is designed to automatically cancel orders that have been pending for 72 hours. In the event of non-action within this timeframe, the system initiates the cancellation process and refunds the money to the buyer.'],
            ['user_id' => 1, 'question' => 'Can users extend the 72-hour auto-cancellation timeframe?', 'answer' => 'Yes, users have the option to extend the auto-cancellation timeframe by an additional 72 hours if the order has not been canceled. This flexibility allows for adjustments in case there are valid reasons to delay the cancellation process.'],
            ['user_id' => 1, 'question' => 'How does the Auto-Release System work on Whales Market?', 'answer' => 'The Auto-Release System on Whales Market automatically releases funds for orders that have been marked by the store as delivered, sent, or dispatched. If there is no further action within 72 hours, the system completes the release, transferring the funds to the store.'],
            ['user_id' => 1, 'question' => 'What is the Auto-Cancellation System on Whales Market?', 'answer' => 'The Auto-Cancellation System on Whales Market automatically cancels orders pending for 72 hours. Users can extend the period for an additional 72 hours if necessary. It ensures a smooth cancellation process and refunds the money to the buyer.'],
            ['user_id' => 1, 'question' => 'Is there an option to extend the 72-hour auto-release timeframe?', 'answer' => 'Yes, similar to the auto-cancellation feature, users can extend the 72-hour auto-release timeframe if necessary. This gives both buyers and sellers the flexibility to accommodate specific situations that may cause delays in the order completion process.'],

            ['user_id' => 1, 'question' => 'How many support tickets can I create per day for regular user-related issues?', 'answer' => 'Regular users are limited to creating a maximum of three support tickets per day for their inquiries or issues.'],
            ['user_id' => 1, 'question' => 'Is there a support ticket limit for stores on Whales Market?', 'answer' => 'Yes, stores on Whales Market can create up to five support tickets per day to address their specific concerns or inquiries.'],

            ['user_id' => 1, 'question' => 'What should I do if I find a bug on Whales Market?', 'answer' => 'If you encounter a bug on Whales Market, navigate to the settings menu and look for the "Bug Report" option. Use this feature to report the bug by providing detailed information, including steps to reproduce the issue. Whales Market encourages users to share comprehensive details for a more effective resolution.'],
            ['user_id' => 1, 'question' => 'Are there any incentives for reporting bugs on Whales Market?', 'answer' => 'Yes, Whales Market values the contribution of users in identifying and reporting bugs. Users who report bugs and provide helpful information may be eligible for rewards or prizes. This encourages active participation in enhancing the platform\'s functionality.'],
            ['user_id' => 1, 'question' => 'Why doesn\'t Whales Market integrate third-party apps for notifications?', 'answer' => 'Whales Market has a powerful and integrated notifications system that covers almost all changes made within the platform. To ensure security, efficiency, and a seamless user experience, the platform does not incorporate third-party apps for notifications.'],

            ['user_id' => 1, 'question' => 'How do I deposit funds into my Whales Market account?', 'answer' => 'To deposit funds, go to the settings menu and look for the "Deposit" option on Whales Market. Follow the provided steps, and you can make a deposit without incurring any fees or having a minimum deposit requirement. Ensure you use the provided deposit address only once for security reasons.'],
            ['user_id' => 1, 'question' => 'Can I use the deposit address multiple times?', 'answer' => 'For security reasons, Whales Market recommends using the deposit address provided only once. Generating a new deposit address for each transaction enhances the security of your funds.'],
            ['user_id' => 1, 'question' => 'How do I withdraw funds from my Whales Market account?', 'answer' => 'To withdraw funds, navigate to the settings menu and look for the "Withdraw" option on Whales Market. Follow the provided steps to initiate a withdrawal. Note that Whales Market does not charge any fees for withdrawals, and there is no minimum withdrawal requirement.'],
            ['user_id' => 1, 'question' => 'How long does it take for a withdrawal to be processed on Whales Market?', 'answer' => 'The withdrawal time frame on Whales Market can vary depending on network conditions. Once initiated, withdrawals are typically processed promptly. Users are encouraged to check their transaction history for updates on the withdrawal status.'],
            ['user_id' => 1, 'question' => 'Are there any restrictions on the number of withdrawals I can make per day?', 'answer' => 'Whales Market typically does not impose restrictions on the number of withdrawals a user can make per day. Users can withdraw funds based on their preferences and needs.'],
            ['user_id' => 1, 'question' => 'Why is 2FA (Two-Factor Authentication) required for opening a store on Whales Market?', 'answer' => '2FA is required to enhance the security of your store on Whales Market. It ensures that only authorized users with the correct authentication method can access and manage the store. Make sure your 2FA is enabled and matches your public name.'],
            ['user_id' => 1, 'question' => 'What should I do if I encounter issues while opening my store on Whales Market?', 'answer' => 'If you encounter issues while opening your store, you can reach out to Whales Market support for assistance. They can provide guidance, address concerns, and ensure a smooth process for setting up your store'],
            ['user_id' => 1, 'question' => 'What should I know', 'answer' => 'Stay safe, find Harm Reduction on dread, find DarkNet user bible on dread, stay conneceted on dread and pitch forums!'],


            // Add more FAQs as needed
        ];


        foreach ($faqs as $faq) {
            FAQ::create($faq);
        }
    }
}
